apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: tenant2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tenant
                operator: In
                values:
                - b
      tolerations:
      - key: "tenant"
        operator: "Equal"
        value: "b"
        effect: "NoSchedule"
      containers:
      - name: java-app
        image: openjdk:11-jre
        ports:
        - containerPort: 8080